pretrained_model_name_or_path: runwayml/stable-diffusion-v1-5
revision: null
variant: null
dataset_name: null
dataset_config_name: null
train_data_dir: "F:\\MLOps\\MLOps_SD\\Dataset\\cvpicturestest"
image_column: image
caption_column: text
validation_prompt: Professional portrait for a CV. The person should appear in business outfit, with a white background suitable for professional settings.
num_validation_images: 2
validation_epochs: 1
max_train_samples: null
output_dir: "F:\\MLOps\\MLOps_SD\\output"
cache_dir: "F:\\MLOps\\MLOps_SD\\cache"
seed: 42069
resolution: 512
center_crop: false
random_flip: false
train_batch_size: 16
num_train_epochs: 20
max_train_steps: null
gradient_accumulation_steps: 1
gradient_checkpointing: false
learning_rate: 1e-4
scale_lr: false
lr_scheduler: constant
lr_warmup_steps: 500
snr_gamma: null
use_8bit_adam: false
allow_tf32: false
dataloader_num_workers: 0
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1e-2
adam_epsilon: 1e-08
max_grad_norm: 1.0
push_to_hub: false
hub_token: null
prediction_type: null
hub_model_id: null
logging_dir: logs
mixed_precision: null
report_to: null
local_rank: -1
checkpointing_steps: 500
checkpoints_total_limit: null
resume_from_checkpoint: null
enable_xformers_memory_efficient_attention: false
noise_offset: 0
rank: 4
