pretrained_model_name_or_path: dreamlike-art/dreamlike-photoreal-2.0
revision: null
variant: null
train_data_dir: "./data/raw"
image_column: image
caption_column: text
validation_prompt: Professional portrait for a CV. The female should appear in business outfit, with a white plain background suitable for professional settings.
num_validation_images: 2
validation_epochs: 1
output_dir: "./models"
cache_dir: "./models/cache"
seed: 42069
resolution: 512
center_crop: false
random_flip: false
train_batch_size: 8
num_train_epochs: 100
max_train_steps: null
gradient_accumulation_steps: 1
gradient_checkpointing: false
learning_rate: 1e-4
scale_lr: false
lr_scheduler: constant
lr_warmup_steps: 500
snr_gamma: null
allow_tf32: false
dataloader_num_workers: 2
adam_beta1: 0.9
adam_beta2: 0.999
adam_weight_decay: 1e-2
adam_epsilon: 1e-08
max_grad_norm: 1.0
prediction_type: null
logging_dir: logs
mixed_precision: null
local_rank: -1
checkpointing_steps: 9999
checkpoints_total_limit: null
resume_from_checkpoint: null
noise_offset: 0
rank: 4
processed_dataset_path: "./data/processed"
WANDB_API_KEY: your_actual_wandb_api_key
PROJECT_NAME: model-registry
ENTITY: banjuessing-LMU Munich
ARTIFACT_NAME: lorasd:latest
