site_name: mlops_project_2024
site_author: Luyang Chu, Jan Büssing, Setareh Toodeh Fadavi, Thi Thuy Pham
docs_dir: source

theme:
  language: en
  name: material
  features:
    - content.code.copy
    - content.code.annotate

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            show_root_heading: true
            separate_signature: true
            show_signature_annotations: true

nav:
  - Home: index.md
