name: Pre-commit CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  pre-commit:
    name: Check pre-commit
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]

    permissions:
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Git
      run: |
        git config --global user.name 'thuyptt'
        git config --global user.email 'thuyptt93@gmailcom'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install pre-commit
      uses: pre-commit/action@v3.0.1
      continue-on-error: true

    - name: List modified files
      run: |
        git diff --name-only

    - name: Commit changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Pre-commit fixes
        commit_options: '--no-verify'
