name: "Run tests"

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]


    steps:
    - name: Checkout
      uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11
        cache: 'pip' # caching pip dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_tests.txt
        pip install pytest
    - name: Set PYTHONPATH (to run make_data.py and train_model.py) + Test with pytest
      run: |
          $env:PYTHONPATH = "$(Get-Location)\mlops_project_2024\data;$env:PYTHONPATH"
          echo "PYTHONPATH=$(pwd)/mlops_project_2024:\$PYTHONPATH" >> $GITHUB_ENV
          pytest -v
